#+title: Docker Parallels Desktop
#+author: Frank Patz-Brockmann

* Docker for Parallels Desktop

  This projects provisions a virtual machine with Parallels Desktop
  for Mac that runs the Docker daemon. It is intended as a replacement
  for Docker Desktop, docker-machine etc. to quickly set up Docker
  without running a separate hypervisor.

  Advantages:

  - more up-to-date Docker version than projects that rely on
    ~boot2docker~
  - re-uses existing Parallels Desktop hypervisor
  - folder sharing with Parallels Desktop, which is enormously faster
    than other hypervisors

* Prerequisites

  - Paralles Desktop for Mac (Pro edition)
  - Docker CLI on your Mac
  - Vagrant
  - The Parallels provider for Vagrant

    #+begin_src shell
      brew install docker vagrant
      vagrant plugin install vagrant-parallels
    #+end_src

* Usage

  Simply run ~vagrant up~ in this directory. It will provision a new
  VM based on ~bento/ubuntu-24.04~, install an up-to-date Docker
  daemon, generate TLS certificates and create a new Docker context
  named ~docker-parallels~ on your Mac, that is activated
  automatically.

* Notes

  - *Bug 2025-02-01* Parallels 20.2 comes with a bug that breaks the
    ~prl_fs~ fstype, therefore host file systems from macOS cannot be
    mounted into the docker machine; workaround are either to stay
    with Parallels 20.1.3 or to downgrade to Parallels 19.

  - the VM is provisioned to share ~/Users~ with the Mac; this makes
    it easy to add Mac directories as volumes to Docker containers
    using the same pathes as on the Mac: 

    #+begin_src shell
      docker run -it -v `pwd`:`pwd` alpine
    #+end_src

  - Parallels will automatically add the VM to ~/etc/hosts~ on the Mac
    under the name ~dockerhost~; thus servers in Docker containers can
    be reached from the Mac as ~dockerhost:<port>~, e.g. this
    container:

    #+begin_src shell
      docker run -p 8080:80 nginx
    #+end_src

    ... would be here http://dockerhost:8080

  - implementation: the VM is provisioned by ~provision.sh~; adding
    the Docker context to the Mac is done by ~host.sh~. Both scripts
    are automatically run by Vagrant on ~up~ and
    ~provision~. Reprovisioning can be done while the VM is already
    running and will recreate the Docker context.

    Feel free to hack on the scripts and drop me a MR.
